services:
  postgis:
    image: 'postgis/postgis:16-3.4'
    environment:
      - 'POSTGRES_DB=gis'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
          - pgdata:/var/lib/postgresql/data
          - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          - ./data/csv:/csv

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgis

volumes:
  pgdata: